version: '3.7'

services:
  db:
    image: postgres:14.2-alpine
    container_name: tfdb-prod
    env_file:
      - ./digrefserver/.env
    volumes:
      - db-prod:/var/lib/postgresql/data
    networks:
      network-prod:
        ipv4_address: 172.172.0.2
    ports:
      - "15123:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d tfdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: tfapp-prod
    ports:
      - "8889:8889"
    networks:
      network-prod:
        ipv4_address: 172.172.0.3
    volumes:
      - .:/usr/bin/tfapp
    env_file:
      - ./digrefserver/.env
    restart: always
    depends_on:
      - db
      - redis
    links:
      - "db:db"

  pgadmin:
    container_name: pgadmin-prod
    image: dpage/pgadmin4:6.10
    env_file:
      - ./digrefserver/.env
    restart: always
    networks:
      network-prod:
        ipv4_address: 172.172.0.4
    volumes:
      - pgadmin-prod:/var/lib/pgadmin
    ports:
      - "5055:80"

  redis:
    container_name: tfredis-prod
    image: redis:7.0.3-alpine
    networks:
      network-prod:
        ipv4_address: 172.172.0.5
    restart: always
    volumes:
      - redis-prod:/data

  celery:
    container_name: tfcelery-prod
    build: .
    networks:
      network-prod:
        ipv4_address: 172.172.0.6
    volumes:
      - .:/usr/bin/tfapp
    env_file:
      - ./digrefserver/.env
    command: celery -A digrefserver worker -l INFO
    restart: always
    depends_on:
      - db
      - redis
      - app

  celery-beat:
    container_name: tfcelery-beat-prod
    build: .
    networks:
      network-prod:
        ipv4_address: 172.172.0.7
    volumes:
      - .:/usr/bin/tfapp
    env_file:
      - ./digrefserver/.env
    command: celery -A digrefserver beat -l INFO
    restart: always
    depends_on:
      - db
      - redis
      - app


networks:
  network-prod:
    ipam:
      driver: default
      config:
        - subnet: "172.172.0.0/24"
          gateway: "172.172.0.1"

volumes:
  db-prod:
  pgadmin-prod:
  redis-prod:
