# Generated by Django 3.2.12 on 2022-08-30 21:18

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_auto_20220822_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_name',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, max_length=40, null=True, verbose_name='Имя пользователя Telegram'),
        ),
    ]
