# Generated by Django 3.2.12 on 2022-09-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_profile_tg_name'),
        ('auth_app', '0034_alter_objecttag_tagged_object'),
    ]

    operations = [
    ]
