# Generated by Django 3.2.12 on 2022-09-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_merge_20220914_0931'),
        ('auth_app', '0037_auto_20220921_1936'),
    ]

    operations = [
    ]
