# Generated by Django 3.2.12 on 2022-10-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_merge_20220914_0931'),
        ('auth_app', '0052_alter_event_object_selector'),
    ]

    operations = [
    ]
