# Generated by Django 3.2.12 on 2022-10-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_merge_20220922_0949'),
        ('auth_app', '0053_merge_20221013_1938'),
    ]

    operations = [
    ]
